### ISSUE TITLE
AssertionError: assert FLAGS.mode is not None

### ISSUE THREAD

**Issue by gdh756462786** [alibaba/EasyTransfer#13]
Traceback (most recent call last):
  File "/home/share/NLP/ali_easytransformer/text_cls.py", line 33, in <module>
    app = TextClassification()
  File "/home/share/NLP/ali_easytransformer/text_cls.py", line 14, in __init__
    super(TextClassification, self).__init__(**kwargs)
 File "/home/nxz/anaconda3/envs/simbert_env/lib/python3.6/site-packages/easytransfer/engines/model.py", line 627, in __init__
    assert FLAGS.mode is not None
AssertionError

**Comment by gdh756462786** [comment]
Python3.6, tensorflow 1.12.3

**Comment by jerryli1981** [comment]
you need tell engine which mode you use, like train_and_evaluate, train_and_evaluate_on_the_fly
nohup python -u main_finetune.py --workerGPU=1 \
  --mode=train_and_evaluate_on_the_fly  \
  --task_name=${task_name}  \
  --train_input_fp=datasets/${task_name}/train.csv  \
  --eval_input_fp=datasets/${task_name}/dev.csv  \
  --pretrain_model_name_or_path=${pretrain_model_name_or_path}  \
  --train_batch_size=${bs}  \
  --num_epochs=${ep}  \
  --model_dir=/apsarapangu/disk2/jerry.lp/projects/pretrain_language_model/${model_dir_name}  \
  --learning_rate=${lr}  > logs/${model_dir_name}.log 2>&1 &
