### ISSUE TITLE
大哥们！咱啥时候将TensorFlow更新到2.0+呀！

### ISSUE THREAD

**Issue by 1148330040** [alibaba/EasyTransfer#15]
之前用bert4keras和keras-xlnet做albert和xlnet因为一个依赖冲突刚的我头皮发麻，用transformer做bert又是torch和TensorFlow2+来回旋转跳跃，本来看到阿里爸爸把这几个bert类模型整合到一起还是TensorFlow环境下的，但是奈何竟然只支持tf1+，因此在此处恳求各个大佬，看看能不能在百忙之中将TensorFlow给升级到2.0+呀，跪谢！！！！！！！！！！！！！！！

**Comment by minghui** [comment]
tf版本上我们会和阿里云上支持的pai-tf版本同步。tf 2.0对接口的改动比较大，目前我们的分布式优化部分还不兼容。估计还需要些时间升级。。。

**Comment by minghui** [comment]
tf版本上我们会和阿里云上支持的pai-tf版本同步。tf 2.0对接口的改动比较大，目前我们的分布式优化部分还不兼容。估计还需要些时间升级（至少需要一两个月）。。。

**Comment by 1148330040** [comment]
> tf版本上我们会和阿里云上支持的pai-tf版本同步。tf 2.0对接口的改动比较大，目前我们的分布式优化部分还不兼容。估计还需要些时间升级（至少需要一两个月）。。。

**Comment by 1148330040** [comment]
> > tf版本上我们会和阿里云上支持的pai-tf版本同步。tf 2.0对接口的改动比较大，目前我们的分布式优化部分还不兼容。估计还需要些时间升级（至少需要一两个月）。。。

那不错啊，哈哈比我预想中快的多呢，我们这些砖工就指望各位科学研究者了，不急不急，谢谢哈，不用回复，你们忙！
