### ISSUE TITLE
Some questions about adabert

### ISSUE THREAD

**Issue by baiyfbupt** [alibaba/EasyTransfer#5]
In adabert paper, the performance of the model is evaluated with accuracy(e.g. Table 3), including 78.7 on MRPC task.

But [here](https://github.com/alibaba/EasyTransfer/tree/master/scripts/knowledge_distillation#4-%E6%95%88%E6%9E%9C%E8%AF%84%E6%B5%8B) we take it as F1 score?  The accuracy of 70.8 is still lower than 78.7 in the paper.
![image](https://user-images.githubusercontent.com/28884066/93977842-b3723f80-fdad-11ea-8734-dc70ce7c3b82.png)

![image](https://user-images.githubusercontent.com/28884066/93977827-abb29b00-fdad-11ea-8c5c-53273a30d73b.png)

**Comment by minghui** [comment]
Please note that 78.7% is F1 as reported in the paper... 70.8 is Acc.

**Comment by baiyfbupt** [comment]
![image](https://user-images.githubusercontent.com/28884066/93980535-52e50180-fdb1-11ea-8982-e534ba9ffe30.png)
![image](https://user-images.githubusercontent.com/28884066/93980698-8de73500-fdb1-11ea-94c8-3e2666769300.png)
只是确认一下，论文中所有的数据指的都是f1值？

**Comment by yxdyc** [comment]
Yes, the MRPC results in Table 3 and Table 4 are both F1 score.
